# Form implementation generated from reading ui file '.\add_lesson.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_add_lesson(object):
    def setupUi(self, add_lesson):
        add_lesson.setObjectName("add_lesson")
        add_lesson.resize(425, 620)
        add_lesson.setMinimumSize(QtCore.QSize(425, 620))
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(add_lesson)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_title_lesson = QtWidgets.QLabel(parent=add_lesson)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_title_lesson.setFont(font)
        self.label_title_lesson.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_title_lesson.setObjectName("label_title_lesson")
        self.verticalLayout_6.addWidget(self.label_title_lesson)
        self.line = QtWidgets.QFrame(parent=add_lesson)
        self.line.setStyleSheet(" border: none;\n"
"                        background: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_photo = QtWidgets.QLabel(parent=add_lesson)
        self.label_photo.setMinimumSize(QtCore.QSize(0, 200))
        self.label_photo.setText("")
        self.label_photo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_photo.setObjectName("label_photo")
        self.verticalLayout.addWidget(self.label_photo)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=add_lesson)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.timeEdit_start = QtWidgets.QTimeEdit(parent=add_lesson)
        self.timeEdit_start.setStyleSheet("QTimeEdit{\n"
"    background:  rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.timeEdit_start.setObjectName("timeEdit_start")
        self.verticalLayout_2.addWidget(self.timeEdit_start)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=add_lesson)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.timeEdit_end = QtWidgets.QTimeEdit(parent=add_lesson)
        self.timeEdit_end.setStyleSheet("QTimeEdit{\n"
"    background:  rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.timeEdit_end.setObjectName("timeEdit_end")
        self.verticalLayout_3.addWidget(self.timeEdit_end)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(parent=add_lesson)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.comboBox_class = QtWidgets.QComboBox(parent=add_lesson)
        self.comboBox_class.setStyleSheet("QComboBox{\n"
"    background:  rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.comboBox_class.setObjectName("comboBox_class")
        self.verticalLayout_5.addWidget(self.comboBox_class)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(parent=add_lesson)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.verticalLayout_7.addLayout(self.verticalLayout_8)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(parent=add_lesson)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.textEdit_details = QtWidgets.QTextEdit(parent=add_lesson)
        self.textEdit_details.setStyleSheet("QTextEdit{\n"
"    background:  rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.textEdit_details.setObjectName("textEdit_details")
        self.verticalLayout_4.addWidget(self.textEdit_details)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_status = QtWidgets.QLabel(parent=add_lesson)
        self.label_status.setMinimumSize(QtCore.QSize(0, 30))
        self.label_status.setText("")
        self.label_status.setObjectName("label_status")
        self.horizontalLayout_3.addWidget(self.label_status)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_save = QtWidgets.QPushButton(parent=add_lesson)
        self.btn_save.setMinimumSize(QtCore.QSize(110, 30))
        self.btn_save.setStyleSheet("QPushButton {\n"
"                            background: #383838;\n"
"                            color: white;\n"
"                            border-radius: 15px;\n"
"                            }\n"
"\n"
"                            QPushButton:hover {\n"
"                            background-color: #303030;\n"
"                            color: white;\n"
"                            }\n"
"\n"
"                            QPushButton:disabled{\n"
"                            background-color: rgb(222, 222, 222);\n"
"                            }")
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_7.addLayout(self.horizontalLayout)

        self.retranslateUi(add_lesson)
        QtCore.QMetaObject.connectSlotsByName(add_lesson)

    def retranslateUi(self, add_lesson):
        _translate = QtCore.QCoreApplication.translate
        add_lesson.setWindowTitle(_translate("add_lesson", "Registrar Aula"))
        self.label_title_lesson.setText(_translate("add_lesson", "Aula - dd/mm/aaaa"))
        self.label_2.setText(_translate("add_lesson", "Início"))
        self.label_3.setText(_translate("add_lesson", "Término"))
        self.label_5.setText(_translate("add_lesson", "Turma"))
        self.label_6.setText(_translate("add_lesson", "Lista de Presença"))
        self.label_4.setText(_translate("add_lesson", "Observações"))
        self.btn_save.setText(_translate("add_lesson", "Salvar"))
