# Form implementation generated from reading ui file '.\lesson.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_lesson(object):
    def setupUi(self, lesson):
        lesson.setObjectName("lesson")
        lesson.resize(557, 406)
        lesson.setStyleSheet("QDialog {\n"
"    background-color: rgb(24, 24, 24);\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(lesson)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_title_lesson = QtWidgets.QLabel(parent=lesson)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_title_lesson.setFont(font)
        self.label_title_lesson.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_title_lesson.setObjectName("label_title_lesson")
        self.verticalLayout_3.addWidget(self.label_title_lesson)
        self.line = QtWidgets.QFrame(parent=lesson)
        self.line.setStyleSheet(" border: none;\n"
"                        background: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_add = QtWidgets.QPushButton(parent=lesson)
        self.pushButton_add.setMinimumSize(QtCore.QSize(119, 30))
        self.pushButton_add.setStyleSheet("QPushButton {\n"
"                            background: #383838;\n"
"                            color: white;\n"
"                            border-radius: 15px;\n"
"                            }\n"
"\n"
"                            QPushButton:hover {\n"
"                            background-color: #303030;\n"
"                            color: white;\n"
"                            }\n"
"\n"
"                            QPushButton:disabled{\n"
"                            background-color: rgb(222, 222, 222);\n"
"                            }")
        self.pushButton_add.setObjectName("pushButton_add")
        self.horizontalLayout.addWidget(self.pushButton_add)
        self.pushButton_remove = QtWidgets.QPushButton(parent=lesson)
        self.pushButton_remove.setEnabled(False)
        self.pushButton_remove.setMinimumSize(QtCore.QSize(110, 30))
        self.pushButton_remove.setStyleSheet("QPushButton {\n"
"                            background: #383838;\n"
"                            color: white;\n"
"                            border-radius: 15px;\n"
"                            }\n"
"\n"
"                            QPushButton:hover {\n"
"                            background-color: #303030;\n"
"                            color: white;\n"
"                            }\n"
"\n"
"                            QPushButton:disabled{\n"
"                            background-color: rgb(222, 222, 222);\n"
"                            }")
        self.pushButton_remove.setObjectName("pushButton_remove")
        self.horizontalLayout.addWidget(self.pushButton_remove)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_lessons = QtWidgets.QTableWidget(parent=lesson)
        self.tableWidget_lessons.setStyleSheet("/* QTableWidget / QTableView - Dark Modern */\n"
"\n"
"QTableWidget {\n"
"    background-color: rgb(24, 24, 24);\n"
"    color: rgb(220, 220, 220);\n"
"    gridline-color: rgb(45, 45, 45);\n"
"    border: 1px solid rgb(40, 40, 40);\n"
"    border-radius: 10px;\n"
"    font-size: 13px;\n"
"    selection-background-color: rgb(52, 120, 180);\n"
"    selection-color: white;\n"
"}\n"
"\n"
"/* Linhas alternadas */\n"
"QTableWidget::item:alternate {\n"
"    background-color: rgb(28, 28, 28);\n"
"}\n"
"\n"
"/* Hover */\n"
"QTableWidget::item:hover {\n"
"    background-color: rgb(40, 40, 40);\n"
"}\n"
"\n"
"/* Selecionado */\n"
"QTableWidget::item:selected {\n"
"    background-color: rgb(52, 120, 180);\n"
"    color: white;\n"
"}\n"
"\n"
"/* Header horizontal */\n"
"QHeaderView::section {\n"
"    background-color: rgb(32, 32, 32);\n"
"    color: rgb(200, 200, 200);\n"
"    padding: 6px;\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(45, 45, 45);\n"
"    border-right: 1px solid rgb(45, 45, 45);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Header hover */\n"
"QHeaderView::section:hover {\n"
"    background-color: rgb(38, 38, 38);\n"
"}\n"
"\n"
"/* Scrollbars minimalistas */\n"
"QScrollBar:vertical {\n"
"    background: rgb(24, 24, 24);\n"
"    width: 10px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgb(90, 90, 90);\n"
"}\n"
"\n"
"QScrollBar::add-line,\n"
"QScrollBar::sub-line {\n"
"    height: 0;\n"
"}\n"
"\n"
"/* Foco discreto */\n"
"QTableWidget:focus {\n"
"    outline: none;\n"
"}\n"
"")
        self.tableWidget_lessons.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidget_lessons.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableWidget_lessons.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget_lessons.setObjectName("tableWidget_lessons")
        self.tableWidget_lessons.setColumnCount(4)
        self.tableWidget_lessons.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lessons.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lessons.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lessons.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lessons.setHorizontalHeaderItem(3, item)
        self.tableWidget_lessons.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_lessons.verticalHeader().setVisible(False)
        self.tableWidget_lessons.verticalHeader().setHighlightSections(False)
        self.verticalLayout.addWidget(self.tableWidget_lessons)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(lesson)
        QtCore.QMetaObject.connectSlotsByName(lesson)

    def retranslateUi(self, lesson):
        _translate = QtCore.QCoreApplication.translate
        lesson.setWindowTitle(_translate("lesson", "Aulas"))
        self.label_title_lesson.setText(_translate("lesson", "Aulas - dd/mm/aaaa"))
        self.pushButton_add.setText(_translate("lesson", "Adicionar"))
        self.pushButton_remove.setText(_translate("lesson", "Remover"))
        item = self.tableWidget_lessons.horizontalHeaderItem(0)
        item.setText(_translate("lesson", "id"))
        item = self.tableWidget_lessons.horizontalHeaderItem(1)
        item.setText(_translate("lesson", "Nome"))
        item = self.tableWidget_lessons.horizontalHeaderItem(2)
        item.setText(_translate("lesson", "Turma"))
        item = self.tableWidget_lessons.horizontalHeaderItem(3)
        item.setText(_translate("lesson", "N. de Alunos "))
