"""add created_at in Student

Revision ID: 1a0377a5dfd5
Revises: b6bd80dfaf90
Create Date: 2026-01-27 16:41:49.318552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a0377a5dfd5'
down_revision = 'b6bd80dfaf90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'created_at')
    # ### end Alembic commands ###
