"""add birth day and sex to Student

Revision ID: 950934394efc
Revises: bdecd8f37b18
Create Date: 2026-01-15 01:46:48.594219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950934394efc'
down_revision = 'bdecd8f37b18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('date_of_birth', sa.Date(), nullable=False))
    op.add_column('students', sa.Column('sex', sa.Enum('MALE', 'FEMALE', name='sex_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'sex')
    op.drop_column('students', 'date_of_birth')
    # ### end Alembic commands ###
