"""add is_inactive in Student

Revision ID: b6bd80dfaf90
Revises: a2e11f9b4c64
Create Date: 2026-01-27 15:18:22.991270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6bd80dfaf90'
down_revision = 'a2e11f9b4c64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('is_inactive', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'is_inactive')
    # ### end Alembic commands ###
