"""initial

Revision ID: bdecd8f37b18
Revises: 
Create Date: 2026-01-06 16:33:23.628118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdecd8f37b18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('observation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('observation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('belt', sa.Enum('WHITE', 'WHITE_I', 'WHITE_II', 'WHITE_III', 'WHITE_IV', 'BLUE', 'BLUE_I', 'BLUE_II', 'BLUE_III', 'BLUE_IV', 'PURPLE', 'PURPLE_I', 'PURPLE_II', 'PURPLE_III', 'PURPLE_IV', 'BROWN', 'BROWN_I', 'BROWN_II', 'BROWN_III', 'BROWN_IV', 'BLACK', name='belt_enum'), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('observation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('plans')
    op.drop_table('classes')
    # ### end Alembic commands ###
