"""fix relationship between students, plans and classes

Revision ID: d6c4e47fdc5d
Revises: 950934394efc
Create Date: 2026-01-19 12:16:14.641935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c4e47fdc5d'
down_revision = '950934394efc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
