"""create PaymentRecord

Revision ID: ef246a66bb79
Revises: d6c4e47fdc5d
Create Date: 2026-01-19 13:17:05.608703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef246a66bb79'
down_revision = 'd6c4e47fdc5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('observation', sa.String(), nullable=True),
    sa.Column('payment_status', sa.Enum('OPEN', 'PAID', 'OVERDUE', name='payment_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_records')
    # ### end Alembic commands ###
