# Form implementation generated from reading ui file '.\main_view.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 758)
        MainWindow.setStyleSheet("background-color: rgb(24, 24, 24);")
        MainWindow.setIconSize(QtCore.QSize(16, 16))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_left_menu.setStyleSheet("background-color: rgb(33, 33, 33);")
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.left_menu = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.left_menu.setContentsMargins(0, 0, 0, 0)
        self.left_menu.setSpacing(6)
        self.left_menu.setObjectName("left_menu")
        self.layout_top_menu = QtWidgets.QFrame(parent=self.frame_left_menu)
        self.layout_top_menu.setMinimumSize(QtCore.QSize(250, 0))
        self.layout_top_menu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.layout_top_menu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.layout_top_menu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.layout_top_menu.setObjectName("layout_top_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layout_top_menu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.layout_top_menu)
        self.label.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.btn_menu_lessons = QtWidgets.QPushButton(parent=self.layout_top_menu)
        self.btn_menu_lessons.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_menu_lessons.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px solid;\n"
"    border-radius: 20px;\n"
"    text-align: left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:  #303030;\n"
"    color: white;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../../icons/lesson.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_menu_lessons.setIcon(icon)
        self.btn_menu_lessons.setObjectName("btn_menu_lessons")
        self.verticalLayout_2.addWidget(self.btn_menu_lessons)
        self.btn_menu_student = QtWidgets.QPushButton(parent=self.layout_top_menu)
        self.btn_menu_student.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_menu_student.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px solid;\n"
"    border-radius: 20px;\n"
"    text-align: left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:  #303030;\n"
"    color: white;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\../../icons/groups-white.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_menu_student.setIcon(icon1)
        self.btn_menu_student.setObjectName("btn_menu_student")
        self.verticalLayout_2.addWidget(self.btn_menu_student)
        self.btn_menu_message_forwarding = QtWidgets.QPushButton(parent=self.layout_top_menu)
        self.btn_menu_message_forwarding.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_menu_message_forwarding.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px solid;\n"
"    border-radius: 20px;\n"
"    text-align: left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:  #303030;\n"
"    color: white;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\../../icons/administrative.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_menu_message_forwarding.setIcon(icon2)
        self.btn_menu_message_forwarding.setObjectName("btn_menu_message_forwarding")
        self.verticalLayout_2.addWidget(self.btn_menu_message_forwarding)
        self.btn_registers = QtWidgets.QPushButton(parent=self.layout_top_menu)
        self.btn_registers.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_registers.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px solid;\n"
"    border-radius: 20px;\n"
"    text-align: left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:  #303030;\n"
"    color: white;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\../../icons/record_fill.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_registers.setIcon(icon3)
        self.btn_registers.setObjectName("btn_registers")
        self.verticalLayout_2.addWidget(self.btn_registers)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.beta_label = QtWidgets.QLabel(parent=self.layout_top_menu)
        self.beta_label.setText("")
        self.beta_label.setObjectName("beta_label")
        self.verticalLayout_2.addWidget(self.beta_label)
        self.left_menu.addWidget(self.layout_top_menu)
        self.line_2 = QtWidgets.QFrame(parent=self.frame_left_menu)
        self.line_2.setEnabled(True)
        font = QtGui.QFont()
        font.setKerning(True)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.left_menu.addWidget(self.line_2)
        self.frame_license = QtWidgets.QFrame(parent=self.frame_left_menu)
        self.frame_license.setStyleSheet("border-top: 1px")
        self.frame_license.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_license.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_license.setObjectName("frame_license")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_license)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_subscription = QtWidgets.QLabel(parent=self.frame_license)
        self.label_subscription.setStyleSheet("color: white;")
        self.label_subscription.setText("")
        self.label_subscription.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_subscription.setObjectName("label_subscription")
        self.verticalLayout_14.addWidget(self.label_subscription)
        self.label_copywrite = QtWidgets.QLabel(parent=self.frame_license)
        self.label_copywrite.setStyleSheet("color: white;")
        self.label_copywrite.setText("")
        self.label_copywrite.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_copywrite.setObjectName("label_copywrite")
        self.verticalLayout_14.addWidget(self.label_copywrite)
        self.left_menu.addWidget(self.frame_license)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.stacked_pages = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stacked_pages.setStyleSheet("")
        self.stacked_pages.setObjectName("stacked_pages")
        self.page_lesson = QtWidgets.QWidget()
        self.page_lesson.setObjectName("page_lesson")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_lesson)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(parent=self.page_lesson)
        self.frame.setStyleSheet("QFrame {\n"
"margin-left: 0px;}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_page_account = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_page_account.setFont(font)
        self.label_page_account.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_page_account.setObjectName("label_page_account")
        self.verticalLayout.addWidget(self.label_page_account)
        self.line_page_account = QtWidgets.QFrame(parent=self.frame)
        self.line_page_account.setStyleSheet(" border: none;\n"
"                        background: rgb(255, 255, 255);")
        self.line_page_account.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_page_account.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_page_account.setObjectName("line_page_account")
        self.verticalLayout.addWidget(self.line_page_account)
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=self.frame)
        self.calendarWidget.setStyleSheet("/* QCalendarWidget - Estilo Moderno */\n"
"QCalendarWidget {\n"
"    background-color: rgb(32, 32, 32);\n"
"    border: 1px solid rgb(60, 60, 60);\n"
"    border-radius: 12px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"/* Barra de navegação superior */\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar {\n"
"    background-color: rgb(40, 40, 40);\n"
"    border-radius: 0px;\n"
"    padding: 4px;\n"
"    margin-bottom: 0px;\n"
"}\n"
"\n"
"/* Botões de navegação (anterior/próximo) */\n"
"QCalendarWidget QToolButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 1px solid rgb(70, 70, 70);\n"
"    border-radius: 6px;\n"
"    color: rgb(220, 220, 220);\n"
"    padding: 6px;\n"
"    margin: 2px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QCalendarWidget QToolButton:hover {\n"
"    background-color: rgb(70, 130, 255);\n"
"    border-color: rgb(90, 150, 255);\n"
"}\n"
"\n"
"QCalendarWidget QToolButton:pressed {\n"
"    background-color: rgb(50, 110, 235);\n"
"}\n"
"\n"
"/* Botão do menu (dropdown ano/mês) */\n"
"QCalendarWidget QToolButton::menu-indicator {\n"
"    image: none;\n"
"    width: 0px;\n"
"}\n"
"\n"
"/* Setas de navegação */\n"
"QCalendarWidget QToolButton#qt_calendar_prevmonth {\n"
"    qproperty-icon: url(none);\n"
"    qproperty-text: \"<\";\n"
"}\n"
"\n"
"QCalendarWidget QToolButton#qt_calendar_nextmonth {\n"
"    qproperty-icon: url(none);\n"
"    qproperty-text: \">\";\n"
"}\n"
"\n"
"/* Botão de seleção de mês */\n"
"QCalendarWidget QToolButton#qt_calendar_monthbutton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: rgb(70, 130, 255);\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QCalendarWidget QToolButton#qt_calendar_monthbutton:hover {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"/* Botão de seleção de ano */\n"
"QCalendarWidget QToolButton#qt_calendar_yearbutton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: rgb(70, 130, 255);\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QCalendarWidget QToolButton#qt_calendar_yearbutton:hover {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"/* Menu dropdown para mês/ano */\n"
"QCalendarWidget QMenu {\n"
"    background-color: rgb(40, 40, 40);\n"
"    border: 1px solid rgb(70, 70, 70);\n"
"    border-radius: 8px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QCalendarWidget QMenu::item {\n"
"    padding: 6px 20px;\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QCalendarWidget QMenu::item:selected {\n"
"    background-color: rgb(70, 130, 255);\n"
"}\n"
"\n"
"/* SpinBox para navegação de ano */\n"
"QCalendarWidget QSpinBox {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 1px solid rgb(70, 70, 70);\n"
"    border-radius: 6px;\n"
"    color: rgb(220, 220, 220);\n"
"    padding: 4px 8px;\n"
"    selection-background-color: rgb(70, 130, 255);\n"
"}\n"
"\n"
"QCalendarWidget QSpinBox::up-button,\n"
"QCalendarWidget QSpinBox::down-button {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCalendarWidget QSpinBox::up-button:hover,\n"
"QCalendarWidget QSpinBox::down-button:hover {\n"
"    background-color: rgb(70, 130, 255);\n"
"}\n"
"\n"
"/* Tabela do calendário */\n"
"QCalendarWidget QTableView {\n"
"    background-color: rgb(32, 32, 32);\n"
"    border: none;\n"
"    selection-background-color: rgb(70, 130, 255);\n"
"    selection-color: white;\n"
"    outline: none;\n"
"    gridline-color: rgb(45, 45, 45);\n"
"}\n"
"\n"
"/* Cabeçalho (dias da semana) */\n"
"QCalendarWidget QTableView QHeaderView::section {\n"
"    background-color: #323232;\n"
"    color: rgb(150, 150, 150);\n"
"    padding: 8px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"    font-size: 11px;\n"
"    text-transform: uppercase;\n"
"}\n"
"\n"
"/* Células do calendário */\n"
"QCalendarWidget QAbstractItemView {\n"
"    color: rgb(220, 220, 220);\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QCalendarWidget QAbstractItemView:enabled {\n"
"    color: rgb(220, 220, 220);\n"
"}\n"
"\n"
"QCalendarWidget QAbstractItemView:disabled {\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"\n"
"/* Dia atual */\n"
"QCalendarWidget QAbstractItemView:enabled {\n"
"    selection-background-color: rgb(70, 130, 255);\n"
"    selection-color: white;\n"
"}\n"
"\n"
"/* Células do calendário - sem efeito de fundo */\n"
"QCalendarWidget QTableView::item {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QCalendarWidget QTableView::item:hover {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Dia selecionado */\n"
"QCalendarWidget QTableView::item:selected {\n"
"    background-color: rgb(70, 130, 255);\n"
"    color: white;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Dias de outros meses (desabilitados) */\n"
"QCalendarWidget QTableView::item:disabled {\n"
"    color: rgb(80, 80, 80);\n"
"}\n"
"\n"
"/* Scrollbars (caso apareçam) */\n"
"QCalendarWidget QScrollBar:vertical {\n"
"    background-color: rgb(32, 32, 32);\n"
"    width: 12px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QCalendarWidget QScrollBar::handle:vertical {\n"
"    background-color: rgb(70, 70, 70);\n"
"    border-radius: 6px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QCalendarWidget QScrollBar::handle:vertical:hover {\n"
"    background-color: rgb(90, 90, 90);\n"
"}\n"
"\n"
"QCalendarWidget QScrollBar::add-line:vertical,\n"
"QCalendarWidget QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}")
        self.calendarWidget.setMinimumDate(QtCore.QDate(2024, 3, 1))
        self.calendarWidget.setMaximumDate(QtCore.QDate(2100, 12, 31))
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.HorizontalHeaderFormat.ShortDayNames)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.VerticalHeaderFormat.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout.addWidget(self.calendarWidget)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.frame)
        self.stacked_pages.addWidget(self.page_lesson)
        self.page_student = QtWidgets.QWidget()
        self.page_student.setObjectName("page_student")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.page_student)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_manage_students = QtWidgets.QLabel(parent=self.page_student)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_manage_students.setFont(font)
        self.label_manage_students.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_manage_students.setObjectName("label_manage_students")
        self.verticalLayout_16.addWidget(self.label_manage_students)
        self.line_manage__students = QtWidgets.QFrame(parent=self.page_student)
        self.line_manage__students.setStyleSheet(" border: none;\n"
"                        background: rgb(255, 255, 255);")
        self.line_manage__students.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_manage__students.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_manage__students.setObjectName("line_manage__students")
        self.verticalLayout_16.addWidget(self.line_manage__students)
        self.layout_buttons_manage_students = QtWidgets.QHBoxLayout()
        self.layout_buttons_manage_students.setObjectName("layout_buttons_manage_students")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layout_buttons_manage_students.addItem(spacerItem1)
        self.btn_add_student = QtWidgets.QPushButton(parent=self.page_student)
        self.btn_add_student.setMinimumSize(QtCore.QSize(130, 30))
        self.btn_add_student.setMaximumSize(QtCore.QSize(250, 30))
        self.btn_add_student.setStyleSheet("QPushButton {\n"
"                            background: #383838;\n"
"                            color: white;\n"
"                            border-radius: 15px;\n"
"                            }\n"
"\n"
"                            QPushButton:hover {\n"
"                            background-color: #303030;\n"
"                            color: white;\n"
"                            }\n"
"\n"
"                            QPushButton:disabled{\n"
"                            background-color: rgb(222, 222, 222);\n"
"                            }")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(".\\../../../../../2tec/engagement-telegram/views/icons/plus.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_add_student.setIcon(icon4)
        self.btn_add_student.setObjectName("btn_add_student")
        self.layout_buttons_manage_students.addWidget(self.btn_add_student)
        self.btn_remove_student = QtWidgets.QPushButton(parent=self.page_student)
        self.btn_remove_student.setEnabled(False)
        self.btn_remove_student.setMinimumSize(QtCore.QSize(130, 30))
        self.btn_remove_student.setMaximumSize(QtCore.QSize(250, 30))
        self.btn_remove_student.setStyleSheet("QPushButton {\n"
"                            background: #383838;\n"
"                            color: white;\n"
"                            border-radius: 15px;\n"
"                            }\n"
"\n"
"                            QPushButton:hover {\n"
"                            background-color: #303030;\n"
"                            color: white;\n"
"                            }\n"
"\n"
"                            QPushButton:disabled{\n"
"                            background-color: rgb(222, 222, 222);\n"
"                            }")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(".\\../../../../../2tec/engagement-telegram/views/icons/delete.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_remove_student.setIcon(icon5)
        self.btn_remove_student.setObjectName("btn_remove_student")
        self.layout_buttons_manage_students.addWidget(self.btn_remove_student)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layout_buttons_manage_students.addItem(spacerItem2)
        self.verticalLayout_16.addLayout(self.layout_buttons_manage_students)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_total = QtWidgets.QLabel(parent=self.page_student)
        self.label_total.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_total.setObjectName("label_total")
        self.horizontalLayout_8.addWidget(self.label_total)
        self.comboBox_filter_student = QtWidgets.QComboBox(parent=self.page_student)
        self.comboBox_filter_student.setStyleSheet("QComboBox{\n"
"    background:  #383838;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.comboBox_filter_student.setObjectName("comboBox_filter_student")
        self.horizontalLayout_8.addWidget(self.comboBox_filter_student)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout_16.addLayout(self.horizontalLayout_8)
        self.table_students = QtWidgets.QTableWidget(parent=self.page_student)
        self.table_students.setStyleSheet("QTableWidget{\n"
"                                background: #F0F3F6;\n"
"                                border: none;\n"
"                                border-radius: 20px;\n"
"                                selection-background-color: #d5e3f2;\n"
"                                selection-color: inherit;\n"
"                                }\n"
"\n"
"                                QHeaderView::section {\n"
"                                background-color: #E3E9EF;\n"
"                                border: none;\n"
"                                height: 32px;\n"
"                                }\n"
"\n"
"                                QHeaderView::section:first {\n"
"                                border-top-left-radius: 20px;\n"
"                                }\n"
"\n"
"\n"
"                                QHeaderView::section:last {\n"
"                                border-top-right-radius: 20px;\n"
"                                }\n"
"                              ")
        self.table_students.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table_students.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.table_students.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table_students.setObjectName("table_students")
        self.table_students.setColumnCount(5)
        self.table_students.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_students.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_students.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_students.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_students.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_students.setHorizontalHeaderItem(4, item)
        self.table_students.horizontalHeader().setStretchLastSection(True)
        self.table_students.verticalHeader().setVisible(False)
        self.table_students.verticalHeader().setDefaultSectionSize(45)
        self.verticalLayout_16.addWidget(self.table_students)
        self.stacked_pages.addWidget(self.page_student)
        self.page_administrative = QtWidgets.QWidget()
        self.page_administrative.setStyleSheet("")
        self.page_administrative.setObjectName("page_administrative")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_administrative)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_page_administrative = QtWidgets.QLabel(parent=self.page_administrative)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_page_administrative.setFont(font)
        self.label_page_administrative.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_page_administrative.setObjectName("label_page_administrative")
        self.verticalLayout_4.addWidget(self.label_page_administrative)
        self.line_page_administrative = QtWidgets.QFrame(parent=self.page_administrative)
        self.line_page_administrative.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_page_administrative.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_page_administrative.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_page_administrative.setObjectName("line_page_administrative")
        self.verticalLayout_4.addWidget(self.line_page_administrative)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.tabWidget_2 = QtWidgets.QTabWidget(parent=self.page_administrative)
        self.tabWidget_2.setStyleSheet("\n"
"QTabWidget::pane {\n"
"    border: 1px solid #cfcfcf;\n"
"    background: #f9f9f9;\n"
"    border-radius: 4px;\n"
"    top: -1px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: #e6e6e6;\n"
"    border: 1px solid #cfcfcf;\n"
"    border-bottom: none;\n"
"    padding: 6px 14px;\n"
"    margin-right: 2px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    color: #444;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #ffffff;\n"
"    color: #222;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: #f2f2f2;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    alignment: left;\n"
"}\n"
"")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_plan = QtWidgets.QWidget()
        self.tab_plan.setStyleSheet("")
        self.tab_plan.setObjectName("tab_plan")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.tab_plan)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.btn_add_plan = QtWidgets.QPushButton(parent=self.tab_plan)
        self.btn_add_plan.setMinimumSize(QtCore.QSize(110, 30))
        self.btn_add_plan.setMaximumSize(QtCore.QSize(250, 30))
        self.btn_add_plan.setStyleSheet("QPushButton {\n"
"                            background: #383838;\n"
"                            color: white;\n"
"                            border-radius: 15px;\n"
"                            }\n"
"\n"
"                            QPushButton:hover {\n"
"                            background-color: #303030;\n"
"                            color: white;\n"
"                            }\n"
"\n"
"                            QPushButton:disabled{\n"
"                            background-color: rgb(222, 222, 222);\n"
"                            }")
        self.btn_add_plan.setObjectName("btn_add_plan")
        self.horizontalLayout_3.addWidget(self.btn_add_plan)
        self.btn_remove_plan = QtWidgets.QPushButton(parent=self.tab_plan)
        self.btn_remove_plan.setMinimumSize(QtCore.QSize(110, 30))
        self.btn_remove_plan.setMaximumSize(QtCore.QSize(250, 30))
        self.btn_remove_plan.setStyleSheet("QPushButton {\n"
"                            background: #383838;\n"
"                            color: white;\n"
"                            border-radius: 15px;\n"
"                            }\n"
"\n"
"                            QPushButton:hover {\n"
"                            background-color: #303030;\n"
"                            color: white;\n"
"                            }\n"
"\n"
"                            QPushButton:disabled{\n"
"                            background-color: rgb(222, 222, 222);\n"
"                            }")
        self.btn_remove_plan.setObjectName("btn_remove_plan")
        self.horizontalLayout_3.addWidget(self.btn_remove_plan)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_15.addLayout(self.horizontalLayout_3)
        self.table_plan = QtWidgets.QTableWidget(parent=self.tab_plan)
        self.table_plan.setStyleSheet("QTableWidget{\n"
"                                background: #F0F3F6;\n"
"                                border: none;\n"
"                                border-radius: 20px;\n"
"                                selection-background-color: #d5e3f2;\n"
"                                selection-color: inherit;\n"
"                                }\n"
"\n"
"                                QHeaderView::section {\n"
"                                background-color: #E3E9EF;\n"
"                                border: none;\n"
"                                height: 32px;\n"
"                                }\n"
"\n"
"                                QHeaderView::section:first {\n"
"                                border-top-left-radius: 20px;\n"
"                                }\n"
"\n"
"\n"
"                                QHeaderView::section:last {\n"
"                                border-top-right-radius: 20px;\n"
"                                }\n"
"                              ")
        self.table_plan.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table_plan.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.table_plan.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table_plan.setObjectName("table_plan")
        self.table_plan.setColumnCount(5)
        self.table_plan.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_plan.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_plan.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_plan.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_plan.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_plan.setHorizontalHeaderItem(4, item)
        self.table_plan.horizontalHeader().setStretchLastSection(True)
        self.table_plan.verticalHeader().setVisible(False)
        self.table_plan.verticalHeader().setHighlightSections(False)
        self.verticalLayout_15.addWidget(self.table_plan)
        self.verticalLayout_18.addLayout(self.verticalLayout_15)
        self.tabWidget_2.addTab(self.tab_plan, "")
        self.tab_class = QtWidgets.QWidget()
        self.tab_class.setStyleSheet("")
        self.tab_class.setObjectName("tab_class")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.tab_class)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.btn_add_class = QtWidgets.QPushButton(parent=self.tab_class)
        self.btn_add_class.setMinimumSize(QtCore.QSize(110, 30))
        self.btn_add_class.setMaximumSize(QtCore.QSize(250, 30))
        self.btn_add_class.setStyleSheet("QPushButton {\n"
"                            background: #383838;\n"
"                            color: white;\n"
"                            border-radius: 15px;\n"
"                            }\n"
"\n"
"                            QPushButton:hover {\n"
"                            background-color: #303030;\n"
"                            color: white;\n"
"                            }\n"
"\n"
"                            QPushButton:disabled{\n"
"                            background-color: rgb(222, 222, 222);\n"
"                            }")
        self.btn_add_class.setObjectName("btn_add_class")
        self.horizontalLayout_5.addWidget(self.btn_add_class)
        self.btn_remove_class = QtWidgets.QPushButton(parent=self.tab_class)
        self.btn_remove_class.setMinimumSize(QtCore.QSize(110, 30))
        self.btn_remove_class.setMaximumSize(QtCore.QSize(250, 30))
        self.btn_remove_class.setStyleSheet("QPushButton {\n"
"                            background: #383838;\n"
"                            color: white;\n"
"                            border-radius: 15px;\n"
"                            }\n"
"\n"
"                            QPushButton:hover {\n"
"                            background-color: #303030;\n"
"                            color: white;\n"
"                            }\n"
"\n"
"                            QPushButton:disabled{\n"
"                            background-color: rgb(222, 222, 222);\n"
"                            }")
        self.btn_remove_class.setObjectName("btn_remove_class")
        self.horizontalLayout_5.addWidget(self.btn_remove_class)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout_17.addLayout(self.horizontalLayout_5)
        self.table_class = QtWidgets.QTableWidget(parent=self.tab_class)
        self.table_class.setStyleSheet("QTableWidget{\n"
"                                background: #F0F3F6;\n"
"                                border: none;\n"
"                                border-radius: 20px;\n"
"                                selection-background-color: #d5e3f2;\n"
"                                selection-color: inherit;\n"
"                                }\n"
"\n"
"                                QHeaderView::section {\n"
"                                background-color: #E3E9EF;\n"
"                                border: none;\n"
"                                height: 32px;\n"
"                                }\n"
"\n"
"                                QHeaderView::section:first {\n"
"                                border-top-left-radius: 20px;\n"
"                                }\n"
"\n"
"\n"
"                                QHeaderView::section:last {\n"
"                                border-top-right-radius: 20px;\n"
"                                }\n"
"                              ")
        self.table_class.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table_class.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.table_class.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table_class.setObjectName("table_class")
        self.table_class.setColumnCount(4)
        self.table_class.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_class.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_class.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_class.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_class.setHorizontalHeaderItem(3, item)
        self.table_class.horizontalHeader().setCascadingSectionResizes(False)
        self.table_class.horizontalHeader().setSortIndicatorShown(False)
        self.table_class.horizontalHeader().setStretchLastSection(True)
        self.table_class.verticalHeader().setVisible(False)
        self.table_class.verticalHeader().setHighlightSections(False)
        self.verticalLayout_17.addWidget(self.table_class)
        self.verticalLayout_19.addLayout(self.verticalLayout_17)
        self.tabWidget_2.addTab(self.tab_class, "")
        self.verticalLayout_5.addWidget(self.tabWidget_2)
        self.stacked_pages.addWidget(self.page_administrative)
        self.page_records = QtWidgets.QWidget()
        self.page_records.setObjectName("page_records")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_records)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_manage_students_2 = QtWidgets.QLabel(parent=self.page_records)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_manage_students_2.setFont(font)
        self.label_manage_students_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_manage_students_2.setObjectName("label_manage_students_2")
        self.verticalLayout_6.addWidget(self.label_manage_students_2)
        self.line_manage__students_2 = QtWidgets.QFrame(parent=self.page_records)
        self.line_manage__students_2.setStyleSheet(" border: none;\n"
"                        background: rgb(255, 255, 255);")
        self.line_manage__students_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_manage__students_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_manage__students_2.setObjectName("line_manage__students_2")
        self.verticalLayout_6.addWidget(self.line_manage__students_2)
        self.label_records_total = QtWidgets.QLabel(parent=self.page_records)
        self.label_records_total.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_records_total.setObjectName("label_records_total")
        self.verticalLayout_6.addWidget(self.label_records_total)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboBox_records_filters = QtWidgets.QComboBox(parent=self.page_records)
        self.comboBox_records_filters.setStyleSheet("QComboBox{\n"
"    background:  #383838;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.comboBox_records_filters.setObjectName("comboBox_records_filters")
        self.horizontalLayout_4.addWidget(self.comboBox_records_filters)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.comboBox_month = QtWidgets.QComboBox(parent=self.page_records)
        self.comboBox_month.setStyleSheet("QComboBox{\n"
"    background:  #383838;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.comboBox_month.setObjectName("comboBox_month")
        self.horizontalLayout_4.addWidget(self.comboBox_month)
        self.comboBox_year = QtWidgets.QComboBox(parent=self.page_records)
        self.comboBox_year.setStyleSheet("QComboBox{\n"
"    background:  #383838;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.comboBox_year.setObjectName("comboBox_year")
        self.horizontalLayout_4.addWidget(self.comboBox_year)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.pushButton_records_reload = QtWidgets.QPushButton(parent=self.page_records)
        self.pushButton_records_reload.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_records_reload.setStyleSheet("QPushButton {\n"
"\n"
"                            background: #383838;\n"
"                            color: white;\n"
"                            border-radius: 100px;\n"
"                            }\n"
"\n"
"                            QPushButton:hover {\n"
"                            background-color: #303030;\n"
"                            color: white;\n"
"                            }\n"
"\n"
"                            QPushButton:disabled{\n"
"                            background-color: rgb(222, 222, 222);\n"
"                            }")
        self.pushButton_records_reload.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(".\\../../icons/refresh_white.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_records_reload.setIcon(icon6)
        self.pushButton_records_reload.setObjectName("pushButton_records_reload")
        self.horizontalLayout_4.addWidget(self.pushButton_records_reload)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.table_students_2 = QtWidgets.QTableWidget(parent=self.page_records)
        self.table_students_2.setStyleSheet("QTableWidget{\n"
"                                background: #F0F3F6;\n"
"                                border: none;\n"
"                                border-radius: 20px;\n"
"                                selection-background-color: #d5e3f2;\n"
"                                selection-color: inherit;\n"
"                                }\n"
"\n"
"                                QHeaderView::section {\n"
"                                background-color: #E3E9EF;\n"
"                                border: none;\n"
"                                height: 32px;\n"
"                                }\n"
"\n"
"                                QHeaderView::section:first {\n"
"                                border-top-left-radius: 20px;\n"
"                                }\n"
"\n"
"\n"
"                                QHeaderView::section:last {\n"
"                                border-top-right-radius: 20px;\n"
"                                }\n"
"                              ")
        self.table_students_2.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table_students_2.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.table_students_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table_students_2.setObjectName("table_students_2")
        self.table_students_2.setColumnCount(4)
        self.table_students_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_students_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_students_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_students_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_students_2.setHorizontalHeaderItem(3, item)
        self.table_students_2.horizontalHeader().setStretchLastSection(True)
        self.table_students_2.verticalHeader().setVisible(False)
        self.table_students_2.verticalHeader().setDefaultSectionSize(45)
        self.verticalLayout_6.addWidget(self.table_students_2)
        self.stacked_pages.addWidget(self.page_records)
        self.horizontalLayout_2.addWidget(self.stacked_pages)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stacked_pages.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "BJJ ADMIN"))
        self.btn_menu_lessons.setText(_translate("MainWindow", "Aulas"))
        self.btn_menu_student.setText(_translate("MainWindow", "Alunos"))
        self.btn_menu_message_forwarding.setText(_translate("MainWindow", "Administrativo"))
        self.btn_registers.setText(_translate("MainWindow", "Registros"))
        self.label_page_account.setText(_translate("MainWindow", "Gerenciar Aulas"))
        self.label_manage_students.setText(_translate("MainWindow", "Gerenciar Alunos"))
        self.btn_add_student.setText(_translate("MainWindow", "Adicionar"))
        self.btn_remove_student.setText(_translate("MainWindow", "Remover"))
        self.label_total.setText(_translate("MainWindow", "Total:"))
        item = self.table_students.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.table_students.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.table_students.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Turma"))
        item = self.table_students.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Contato"))
        item = self.table_students.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Status"))
        self.label_page_administrative.setText(_translate("MainWindow", "Administrativo"))
        self.btn_add_plan.setText(_translate("MainWindow", "Adicionar"))
        self.btn_remove_plan.setText(_translate("MainWindow", "Remover"))
        item = self.table_plan.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.table_plan.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.table_plan.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Valor"))
        item = self.table_plan.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "N. de Alunos"))
        item = self.table_plan.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Detalhes"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_plan), _translate("MainWindow", "Planos"))
        self.btn_add_class.setText(_translate("MainWindow", "Adicionar"))
        self.btn_remove_class.setText(_translate("MainWindow", "Remover"))
        item = self.table_class.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.table_class.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.table_class.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "N. de Alunos"))
        item = self.table_class.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Detalhes"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_class), _translate("MainWindow", "Turmas"))
        self.label_manage_students_2.setText(_translate("MainWindow", "Registros"))
        self.label_records_total.setText(_translate("MainWindow", "Total: ."))
        item = self.table_students_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.table_students_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Aluno"))
        item = self.table_students_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Status"))
        item = self.table_students_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Última Atualização"))
