# Form implementation generated from reading ui file '.\add_plan.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_AddPlan(object):
    def setupUi(self, AddPlan):
        AddPlan.setObjectName("AddPlan")
        AddPlan.resize(550, 350)
        AddPlan.setMinimumSize(QtCore.QSize(550, 350))
        AddPlan.setMaximumSize(QtCore.QSize(550, 350))
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(AddPlan)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_page_account = QtWidgets.QLabel(parent=AddPlan)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_page_account.setFont(font)
        self.label_page_account.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_page_account.setObjectName("label_page_account")
        self.verticalLayout.addWidget(self.label_page_account)
        self.line_page_account = QtWidgets.QFrame(parent=AddPlan)
        self.line_page_account.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_page_account.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_page_account.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_page_account.setObjectName("line_page_account")
        self.verticalLayout.addWidget(self.line_page_account)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=AddPlan)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.line_name = QtWidgets.QLineEdit(parent=AddPlan)
        self.line_name.setMinimumSize(QtCore.QSize(0, 30))
        self.line_name.setStyleSheet("QLineEdit{\n"
"    background:  rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.line_name.setObjectName("line_name")
        self.verticalLayout_2.addWidget(self.line_name)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=AddPlan)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.spin_value = QtWidgets.QDoubleSpinBox(parent=AddPlan)
        self.spin_value.setMinimumSize(QtCore.QSize(0, 30))
        self.spin_value.setStyleSheet("QDoubleSpinBox{\n"
"    background:  rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.spin_value.setMaximum(999999.99)
        self.spin_value.setObjectName("spin_value")
        self.verticalLayout_3.addWidget(self.spin_value)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=AddPlan)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.textEdit_datails = QtWidgets.QTextEdit(parent=AddPlan)
        self.textEdit_datails.setMinimumSize(QtCore.QSize(0, 30))
        self.textEdit_datails.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEdit_datails.setStyleSheet("QTextEdit{\n"
"    background:  rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.textEdit_datails.setObjectName("textEdit_datails")
        self.verticalLayout_4.addWidget(self.textEdit_datails)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_status = QtWidgets.QLabel(parent=AddPlan)
        self.label_status.setText("")
        self.label_status.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.verticalLayout_7.addWidget(self.label_status)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_save = QtWidgets.QPushButton(parent=AddPlan)
        self.btn_save.setMinimumSize(QtCore.QSize(150, 30))
        self.btn_save.setStyleSheet("QPushButton {\n"
"                            background: #383838;\n"
"                            color: white;\n"
"                            border-radius: 15px;\n"
"                            }\n"
"\n"
"                            QPushButton:hover {\n"
"                            background-color: #303030;\n"
"                            color: white;\n"
"                            }\n"
"\n"
"                            QPushButton:disabled{\n"
"                            background-color: rgb(222, 222, 222);\n"
"                            }")
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout_6.addLayout(self.verticalLayout_7)

        self.retranslateUi(AddPlan)
        QtCore.QMetaObject.connectSlotsByName(AddPlan)

    def retranslateUi(self, AddPlan):
        _translate = QtCore.QCoreApplication.translate
        AddPlan.setWindowTitle(_translate("AddPlan", "Cadastrar Plano"))
        self.label_page_account.setText(_translate("AddPlan", "Cadastrar Plano"))
        self.label.setText(_translate("AddPlan", "Nome"))
        self.label_2.setText(_translate("AddPlan", "Valor"))
        self.label_3.setText(_translate("AddPlan", "Detalhes"))
        self.btn_save.setText(_translate("AddPlan", "Salvar"))
