# Form implementation generated from reading ui file '.\add_class.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_AddClass(object):
    def setupUi(self, AddClass):
        AddClass.setObjectName("AddClass")
        AddClass.resize(550, 350)
        AddClass.setMinimumSize(QtCore.QSize(550, 350))
        AddClass.setMaximumSize(QtCore.QSize(550, 350))
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(AddClass)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_page_account = QtWidgets.QLabel(parent=AddClass)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_page_account.setFont(font)
        self.label_page_account.setStyleSheet("color: #4F9AFE")
        self.label_page_account.setObjectName("label_page_account")
        self.verticalLayout.addWidget(self.label_page_account)
        self.line_page_account = QtWidgets.QFrame(parent=AddClass)
        self.line_page_account.setStyleSheet(" border: none;\n"
"                            background: #4F9AFE;")
        self.line_page_account.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_page_account.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_page_account.setObjectName("line_page_account")
        self.verticalLayout.addWidget(self.line_page_account)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=AddClass)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lineEdit_name = QtWidgets.QLineEdit(parent=AddClass)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.verticalLayout_2.addWidget(self.lineEdit_name)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=AddClass)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.textEdit_details = QtWidgets.QTextEdit(parent=AddClass)
        self.textEdit_details.setMinimumSize(QtCore.QSize(0, 0))
        self.textEdit_details.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEdit_details.setObjectName("textEdit_details")
        self.verticalLayout_4.addWidget(self.textEdit_details)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_status = QtWidgets.QLabel(parent=AddClass)
        self.label_status.setText("")
        self.label_status.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.verticalLayout_3.addWidget(self.label_status)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_save = QtWidgets.QPushButton(parent=AddClass)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)

        self.retranslateUi(AddClass)
        QtCore.QMetaObject.connectSlotsByName(AddClass)

    def retranslateUi(self, AddClass):
        _translate = QtCore.QCoreApplication.translate
        AddClass.setWindowTitle(_translate("AddClass", "Cadastrar Turma"))
        self.label_page_account.setText(_translate("AddClass", "Cadastrar Turma"))
        self.label.setText(_translate("AddClass", "Nome"))
        self.label_3.setText(_translate("AddClass", "Detalhes"))
        self.btn_save.setText(_translate("AddClass", "Salvar"))
