# Form implementation generated from reading ui file '.\edit_record_value.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_EditRecordValue(object):
    def setupUi(self, EditRecordValue):
        EditRecordValue.setObjectName("EditRecordValue")
        EditRecordValue.resize(400, 156)
        EditRecordValue.setStyleSheet("QDialog {\n"
"background-color: rgb(24, 24, 24);\n"
"\n"
"}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(EditRecordValue)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=EditRecordValue)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line = QtWidgets.QFrame(parent=EditRecordValue)
        self.line.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=EditRecordValue)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(parent=EditRecordValue)
        self.doubleSpinBox.setMinimumSize(QtCore.QSize(0, 30))
        self.doubleSpinBox.setStyleSheet("QDoubleSpinBox{\n"
"    background:  rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.doubleSpinBox.setMaximum(99999.99)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.verticalLayout_2.addWidget(self.doubleSpinBox)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(parent=EditRecordValue)
        self.pushButton.setMinimumSize(QtCore.QSize(140, 30))
        self.pushButton.setStyleSheet("QPushButton {\n"
"                            background: #383838;\n"
"                            color: white;\n"
"                            border-radius: 15px;\n"
"                            }\n"
"\n"
"                            QPushButton:hover {\n"
"                            background-color: #303030;\n"
"                            color: white;\n"
"                            }\n"
"\n"
"                            QPushButton:disabled{\n"
"                            background-color: rgb(222, 222, 222);\n"
"                            }")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(EditRecordValue)
        QtCore.QMetaObject.connectSlotsByName(EditRecordValue)

    def retranslateUi(self, EditRecordValue):
        _translate = QtCore.QCoreApplication.translate
        EditRecordValue.setWindowTitle(_translate("EditRecordValue", "Editar valor cobrado"))
        self.label.setText(_translate("EditRecordValue", "Editar valor cobrado"))
        self.label_2.setText(_translate("EditRecordValue", "Valor"))
        self.pushButton.setText(_translate("EditRecordValue", "Salvar"))
